backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Blog Posts"
    name: posts
    editor:
      preview: false
    files:
      - label: "Posts"
        name: post
        file: "db.json"
        extension: json
        fields:
          - label: "Blog Post"
            name: posts
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'markdown' }